In [135]:
import numpy as np

In [136]:
X = np.array([[0,0,1]
              ,[0,1,1]
              ,[1,0,1]
              ,[1,1,1]])  

In [137]:
Y = np.array([[0]
              ,[1]
              ,[1]
              ,[0]])

In [138]:
alphas = [0.001,0.01,0.1,1,10,100,1000]
np.random.seed(1)

In [139]:
weight0 = 2*np.random.random((3,4)) -1
weight1 = 2*np.random.random((4,1)) -1

In [140]:
weight0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [141]:
weight1

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [142]:
def nonlin(x, deriv = False):
    if(deriv == True):
        return x*(1-x)
    
    return 1/(1+np.exp(-x))
    

In [143]:
for j in range(10000):
    layer0 = X
    layer1 = nonlin(np.dot(layer0,weight0))
    layer2 = nonlin(np.dot(layer1,weight1))
    
#     if(j%100 ==0):
#         print(layer0)
#         print(layer1)
#         print(layer2)
    
    layer2_error = (Y-layer2)
#     print(layer2_error)
    if(j%100 ==0):
        print("Error is", np.mean(abs(layer2_error)))
    
    layer2_delta = layer2_error*nonlin(layer2, deriv = True)
    layer1_error = layer2_delta.dot(weight1.T)
    layer1_delta = layer1_error*nonlin(layer1, deriv = True)
    
#     if(j%100 ==0):
#         print(layer2_delta)
#         print(layer1_error)
#         print(layer1_delta)
    
    
    weight1 += layer1.T.dot(layer2_delta)*200
    weight0 += layer0.T.dot(layer1_delta)*200
    

Error is 0.496410031903
Error is 0.500046151259
Error is 0.500022328816
Error is 0.500014565446
Error is 0.500010692848
Error is 0.500008345812
Error is 0.500006742144
Error is 0.500005542731
Error is 0.500004567992
Error is 0.500003698668
Error is 0.500002822723
Error is 0.500001770328
Error is 0.500000117259
Error is 0.499995967084
Error is 0.499932717748
Error is 0.500002323795
Error is 0.500002197084
Error is 0.500002083823
Error is 0.500001981876
Error is 0.500001889545
Error is 0.500001805462
Error is 0.50000172851
Error is 0.50000165777
Error is 0.500001592478
Error is 0.50000153199
Error is 0.500001475766
Error is 0.500001423342
Error is 0.500001374321
Error is 0.500001328362
Error is 0.500001285167
Error is 0.500001244478
Error is 0.500001206067
Error is 0.500001169735
Error is 0.500001135304
Error is 0.500001102618
Error is 0.500001071537
Error is 0.500001041936
Error is 0.500001013701
Error is 0.500000986733
Error is 0.50000096094
Error is 0.500000936239
Error is 0.500000912

In [134]:
X_test=[[1,0,1]]
y = nonlin(np.dot(X_test, weight0))

In [125]:
y_ans = nonlin(np.dot(y, weight1))

In [126]:
y_ans

array([[ 0.96202137]])