In [1]:
import numpy as np

In [2]:
X = np.array([[0,0,1]
              ,[0,1,1]
              ,[1,0,1]
              ,[1,1,1]])  

In [3]:
Y = np.array([[0]
              ,[1]
              ,[1]
              ,[0]])

In [22]:
np.random.seed(1)

In [49]:
weight0 = 2*np.random.random((3,4)) -1
weight1 = 2*np.random.random((4,1)) -1

In [50]:
weight0

array([[-0.10017573,  0.15677923, -0.18372639, -0.52594604],
       [ 0.80675904,  0.14735897, -0.99425935,  0.23428983],
       [-0.3467102 ,  0.0541162 ,  0.7718842 , -0.28546048]])

In [51]:
weight1

array([[ 0.8170703 ],
       [ 0.24672023],
       [-0.96835751],
       [ 0.85887447]])

In [52]:
def nonlin(x, deriv = False):
    if(deriv == True):
        return x*(1-x)
    
    return 1/(1+np.exp(-x))
    

In [53]:
for j in range(10000):
    layer0 = X
    layer1 = nonlin(np.dot(layer0,weight0))
    layer2 = nonlin(np.dot(layer1,weight1))
#     print(layer1)
#     print(layer2)
    
    layer2_error = (Y-layer2)
    if(j%100 ==0):
        print("Error is", np.mean(abs(layer2_error)))
    
    layer2_delta = layer2_error*nonlin(layer2, deriv = True)
    layer1_error = layer2_delta.dot(weight1.T)
    layer1_delta = layer1_error*nonlin(layer1, deriv = True)
    
    weight1 += layer1.T.dot(layer2_delta)*.1
    weight0 += layer0.T.dot(layer1_delta)*.1
    

Error is 0.500264198627
Error is 0.499972712178
Error is 0.499901645113
Error is 0.499839135083
Error is 0.499775072013
Error is 0.499709104557
Error is 0.499641621182
Error is 0.499573021966
Error is 0.499503577743
Error is 0.499433372937
Error is 0.499362285638
Error is 0.499289989594
Error is 0.499215967021
Error is 0.499139523961
Error is 0.499059802399
Error is 0.49897578544
Error is 0.498886293303
Error is 0.498789968708
Error is 0.498685250508
Error is 0.498570334244
Error is 0.498443117779
Error is 0.498301129316
Error is 0.498141433999
Error is 0.497960513871
Error is 0.497754114168
Error is 0.497517046794
Error is 0.497242939186
Error is 0.49692391389
Error is 0.496550181046
Error is 0.496109523409
Error is 0.495586652676
Error is 0.494962419157
Error is 0.494212868508
Error is 0.493308166306
Error is 0.492211464155
Error is 0.490877873189
Error is 0.489253855189
Error is 0.487277538556
Error is 0.48488068026
Error is 0.48199311313
Error is 0.478550315359
Error is 0.474503908

In [66]:
X_test=[[1,1,1]]
y = nonlin(np.dot(X_test, weight0))

In [67]:
y_ans = nonlin(np.dot(y, weight1))

In [68]:
y_ans

array([[ 0.05065746]])